# 配置热更新需要在nacos中操作
mybatis:
    mapper-locations: classpath:mappers/*xml
    type-aliases-package: com.example.pay_service.mybatis.entity
server:
    port: 8092
feign:
  okhttp:
      enabled: true
spring:
    cloud:
        nacos:
            discovery:
                server-addr: 47.109.207.105:8848
    servlet:
        multipart:
            max-file-size: 10MB #-1 无限制
            max-request-size: 100MB #指定为100MB -1无限制
    application:
        name: pay_service
    rabbitmq:
      host: 47.109.207.105
      port: 5672
      virtual-host: /bank
      username: bank
      password: 123
      template:
        retry:
          enabled: true
          max-attempts: 3
      publisher-confirm-type: none #返回生产者看是否确认
      publisher-returns: false
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://47.109.207.105:3306/bank?useSSL=false&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: dhbiss12138.
    redis:
        host: 47.109.207.105
        port: 6379
        password: 12138
        lettuce:
            pool:
                max-active: 10
                max-idle: 10
                min-idle: 1
                time-between-eviction-runs: 1000s
    jackson:
        default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.example.pay_service.entity # 别名扫描包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
    level:
        com.school: debug
    pattern:
        dateformat: mm:ss.SSS
smsbao:
    username: jhy123_
    apiKey: c15fae1c98854433addae5e356a1628b
