mybatis:
    mapper-locations: classpath:mappers/*xml
    type-aliases-package: com.example.school.mybatis.entity
server:
    port: 8081
feign:
  okhttp:
      enabled: true
spring:
    main:
      web-application-type: reactive
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.109.207.105:3306/bank?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: dhbiss12138.
    cloud:
      nacos:
        discovery:
          server-addr: 47.109.207.105:8848
      gateway:
        routes:
          - id: school
            uri: lb://school
            predicates:
              - Path=/user/**
          - id: itservice
            uri: lb://itservice
            predicates:
              - Path=/find/**
          - id: blog
            uri: lb://blog
            predicates:
              - Path=/blog/**
    application:
        name: bk-getway
    jackson:
        default-property-inclusion: non_null # JSON处理时忽略非空字段
    redis:
      host: 47.109.207.105
      port: 6379
      password: 12138
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 1000s
logging:
    level:
        com.school: debug
    pattern:
        dateformat: mm:ss.SSS
