# 配置热更新需要在nacos中操作
mybatis:
    mapper-locations: classpath:mappers/*xml
    type-aliases-package: com.example.itservice.mybatis.entity
server:
    port: 8083
feign:
  okhttp:
      enabled: true
spring:
    cloud:
        nacos:
            discovery:
                server-addr: 47.109.207.105:8848
    rabbitmq:
      host: 47.109.207.105
      port: 5672
      virtual-host: /bank
      username: bank
      password: 123
      listener:
        simple:
          prefetch: 1 #每次处理一条消息，处理完再去处理下一条消息
          acknowledge-mode: auto # 确认机制
          retry:
            enabled: true # 开启重试机制
            initial-interval: 1000ms #初始的失败等待时长为1s
            multiplier: 1 #下次失败的等待时长倍数，下次等待时长 = multiplier * last - interval
            max-attempts: 3 #最大重试次数
            stateless: true #true无状态；false有状态，如果业务中包含事务，这里改为false
    servlet:
        multipart:
            max-file-size: 10MB #-1 无限制
            max-request-size: 100MB #指定为100MB -1无限制
    application:
        name: itservice
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://47.109.207.105:3306/bank?useSSL=false&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: dhbiss12138.
    redis:
        host: 47.109.207.105
        port: 6379
        password: 12138
        lettuce:
            pool:
                max-active: 10
                max-idle: 10
                min-idle: 1
                time-between-eviction-runs: 1000s
    jackson:
        default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.example.itservice.entity # 别名扫描包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
    level:
        com.school: debug
    pattern:
        dateformat: mm:ss.SSS
smsbao:
    username: jhy123_
    apiKey: c15fae1c98854433addae5e356a1628b
